apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sensor
  namespace: argo
spec:
  # template:
  #   serviceAccountName: operate-workflow-sa
  dependencies:
    - name: webhook-listener
      eventSourceName: webhook-listener
      eventName: event
  triggers:
    - template:
        name: http-trigger
        http:
          url: https://api.telegram.org/bot$YOUR_KEY/sendMessage
          headers:
            Content-Type: "application/json"
            Accept: "application/json"
          payload: 
            - src:
                value: "$CHAT_ID"
                dependencyName: webhook-listener
              dest: chat_id
            - src:
                dependencyName: webhook-listener
                dataKey: body
              dest: text
          method: POST
      retryStrategy:
        steps: 3
        duration: 3s
    