{
 "title": "Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - homeassistant_state_change_created{entity=~\".*fritz_box_7490_connection_uptime\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{domain=\"binary_sensor\",entity=~\"binary_sensor.sensore_bagno_motion|binary_sensor.sensore_camera_motion\", friendly_name=~\".*sensor.*\"} > 0",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "max(homeassistant_binary_sensor_state{domain=\"binary_sensor\",entity=~\"binary_sensor.sensore_cucina_1_motion|binary_sensor.tradfri_motion_sensor\", friendly_name=~\".*sensor.*\"})  > 0",
     "legendFormat": "Cucina"
    }
   ]
  },
  {
   "title": "Download",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_mbit_per_s{entity=\"sensor.speedtest_download\"}"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_mbit_per_s{entity=\"sensor.speedtest_upload\"}"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_ms{entity=\"sensor.speedtest_ping\"}"
    }
   ]
  },
  {
   "title": "NAS Disk Space",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_percent{domain=\"sensor\", entity=\"sensor.raelix_volume_1_volume_used\", friendly_name=\"raelix Volume Used\", instance=\"supervisor:80\", job=\"home-assistant\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "100 - homeassistant_sensor_unit_percent{domain=\"sensor\", entity=\"sensor.raelix_volume_1_volume_used\", friendly_name=\"raelix Volume Used\", instance=\"supervisor:80\", job=\"home-assistant\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Download",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_mbit_per_s{entity=\"sensor.speedtest_download\"}",
     "legendFormat": "Download Speed"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_mbit_per_s{entity=\"sensor.speedtest_upload\"}",
     "legendFormat": "Upload Speed"
    }
   ]
  },
  {
   "title": "Sent Kb/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_kib_per_s{domain=\"sensor\",entity=\"sensor.fritz_box_7490_kib_s_sent\"}",
     "legendFormat": "Sent Kb/s"
    }
   ]
  },
  {
   "title": "Received Kb/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_kib_per_s{domain=\"sensor\", entity=\"sensor.fritz_box_7490_kib_s_received\"}",
     "legendFormat": "Received Kb/s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{domain=\"binary_sensor\",entity=~\"binary_sensor..*sensor.*\", friendly_name=~\".*sensor.*\"} > 0",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  }
 ]
}