{{- if .Values.serviceMonitor.enabled }}
{{- range .Values.serviceMonitor.targets }}
{{-  $serviceMonitorName := printf "%s-%s" (include "prometheus-json-exporter.fullname" $)  (.name) }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $serviceMonitorName }}
  {{- if $.Values.serviceMonitor.namespace }}
  namespace: {{ $.Values.serviceMonitor.namespace }}
  {{- end }}
  labels:
    {{- include "prometheus-json-exporter.labels" $ | nindent 4 }}
    {{- if or $.Values.serviceMonitor.defaults.labels .labels }}
    {{- toYaml (.labels | default $.Values.serviceMonitor.defaults.labels) | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - port: http
    scheme: {{ $.Values.serviceMonitor.scheme }}
    path: "/probe"
    interval: {{ .interval | default $.Values.serviceMonitor.defaults.interval }}
    {{- if $.Values.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .scrapeTimeout | default $.Values.serviceMonitor.defaults.scrapeTimeout }}
    {{- end }}
    params:
      target:
      - {{ .url }}
    relabelings:
    - regex: "container"
      action: labeldrop
    - regex: "endpoint"
      action: labeldrop
    - regex: "job"
      action: labeldrop
    - regex: "pod"
      action: labeldrop
    - regex: "service"
      action: labeldrop
    - regex: "namespace"
      action: labeldrop
    metricRelabelings:
      - sourceLabels: [instance]
        targetLabel: url
        replacement: {{ .url }}
      - regex: "instance"
        action: labeldrop
      - sourceLabels: [target]
        targetLabel: target
        replacement: {{ .name }}
        {{- range $targetLabel, $replacement := .additionalMetricsRelabels | default $.Values.serviceMonitor.defaults.additionalMetricsRelabels }}
      - targetLabel: {{ $targetLabel }}
        replacement: {{ $replacement }}
        {{- end }}
  jobLabel: "{{ $.Release.Name }}"
  selector:
    matchLabels:
      {{- include "prometheus-json-exporter.selectorLabels" $ | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
{{- end }}
{{- end }}
